"""changes

Revision ID: 289b8acd5f2e
Revises: 8977ac222c39
Create Date: 2026-08-29 09:30:08.192422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289b8acd5f2e'
down_revision: Union[str, Sequence[str], None] = '8977ac222c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'SERVICE', 'ADMIN', name='usertype'), nullable=True))
    op.drop_column('users', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.VARCHAR(length=7), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
