"""Changesssss

Revision ID: 36d368912e25
Revises: 5f0f8c290ea7
Create Date: 2026-08-27 09:33:01.186922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d368912e25'
down_revision: Union[str, Sequence[str], None] = '5f0f8c290ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PROVIDED', 'PENDING', 'REJECTED', name='transactionstatus'), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
