"""changgg

Revision ID: 48c477e6767f
Revises: cd7ec8576b08
Create Date: 2026-08-29 13:46:04.168116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c477e6767f'
down_revision: Union[str, Sequence[str], None] = 'cd7ec8576b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('debt', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('start_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True))
    op.add_column('applications', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'end_date')
    op.drop_column('applications', 'start_date')
    op.drop_column('applications', 'debt')
    op.drop_column('applications', 'balance')
    # ### end Alembic commands ###
