"""Edited card model

Revision ID: 65352e407336
Revises: a0c08b925f5c
Create Date: 2026-08-25 09:11:07.390427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65352e407336'
down_revision: Union[str, Sequence[str], None] = 'a0c08b925f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('pan', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('expiry', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('charge_id', sa.String(), nullable=False))
    op.add_column('cards', sa.Column('bind_ref', sa.String(), nullable=False))
    op.drop_column('cards', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('token', sa.VARCHAR(), nullable=False))
    op.drop_column('cards', 'bind_ref')
    op.drop_column('cards', 'charge_id')
    op.drop_column('cards', 'expiry')
    op.drop_column('cards', 'pan')
    # ### end Alembic commands ###
