"""autopayment

Revision ID: 998846b9dac0
Revises: a462e3cb94d8
Create Date: 2026-09-11 09:03:49.453905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998846b9dac0'
down_revision: Union[str, Sequence[str], None] = 'a462e3cb94d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('next_payment', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'next_payment')
    op.drop_column('applications', 'is_paid')
    # ### end Alembic commands ###
