"""changes

Revision ID: a462e3cb94d8
Revises: 08ba31112123
Create Date: 2026-09-03 18:01:01.576242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a462e3cb94d8'
down_revision: Union[str, Sequence[str], None] = '08ba31112123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_application_id',  # Explicit constraint name required for batch operations
            'applications', 
            ['application_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_application_id', type_='foreignkey')
        batch_op.drop_column('application_id')
    # ### end Alembic commands ###
